version: "3.4"
services:
  node:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - "./app:/var/www/html"
      - "/var/www/html/node_modules"
    ports:
      - 80:8080
      - 8081:8081
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1450